# Generated by Django 3.2 on 2021-04-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guitar_Planner', '0002_backlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backlog',
            new_name='Back_log',
        ),
    ]
