# Generated by Django 3.2 on 2021-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guitar_Planner', '0003_rename_backlog_back_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='month',
        ),
        migrations.AddField(
            model_name='month',
            name='exercise',
            field=models.ManyToManyField(to='Guitar_Planner.Exercise'),
        ),
        migrations.AddField(
            model_name='month',
            name='song',
            field=models.ManyToManyField(to='Guitar_Planner.Song'),
        ),
    ]
